spring.application.name=restaurant
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/central_db
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.multiTenancy=SCHEMA

#spring.central-db.url=jdbc:mysql://localhost:3306/central_db
#spring.central-db.username=root
#spring.central-db.password=123456

spring.cache.type=caffeine

# ========== SERVER THREAD POOL ==========
# c\uFFFD ngh?a l\uFFFD Tomcat s? kh?i t?o s?n 10 (50 ?? d\uFFFDng cho tr?ng h?p c?n ph?c v? nhi?u request h?n ) thread ?? ph?c v? request.
# ?i?u n\uFFFDy s? ti\uFFFDu t?n CPU v\uFFFD RAM ngay khi start server.
server.tomcat.threads.min-spare=10
# S? l??ng thread x? l\uFFFD request ??ng th?i
server.tomcat.threads.max=500
# S? request ch? trong h\uFFFDng ??i khi max-threads full
server.tomcat.accept-count=1000
# M?i request m?t 200ms ?? x? l\uFFFD
# Server c\uFFFD th? x? l\uFFFD 5000 request/gi\uFFFDy (theo l\uFFFD thuy?t) n?u ?? t\uFFFDi nguy\uFFFDn v\uFFFD backend nhanh.

# ========== JPA / Hibernate ==========
#Kh\uFFFDng t?n t\uFFFDi nguy\uFFFDn khi start. hibernate.order_inserts, batch_size, ... gi\uFFFDp t?i ?u hi?u su?t DB v? sau.
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false

# ========== DB CONNECTION POOL ==========
# c\uFFFD th? nh?n 200 connection c\uFFFDng m?t l\uFFFDc
spring.datasource.hikari.maximum-pool-size=200
#S? k?t n?i idle t?i thi?u (k?t n?i r?nh r?i kh\uFFFDng d\uFFFDng) ???c gi? trong pool.
# Hikari s? kh?i t?o 20 k?t n?i DB khi start, ?i?u n\uFFFDy c\uFFFD th? t?n th?i gian n?u:
#DB server ?\uFFFDp ?ng ch?m.
#M?i tenant c\uFFFD k?t n?i ri\uFFFDng ? b?n c?n ch?c ch?n c?u h\uFFFDnh pooling ri\uFFFDng cho t?ng schema l\uFFFD h?p l\uFFFD.
# ?? idle=5 ?? t?n t\uFFFDi nguy\uFFFDn v\uFFFD th?i gian
spring.datasource.hikari.minimum-idle=5
# N?u h?t 30 gi\uFFFDy m\uFFFD kh\uFFFDng c\uFFFD k?t n?i n\uFFFDo ???c c?p, s? n\uFFFDm exception (TimeoutException).
spring.datasource.hikari.connection-timeout=30000
#Th?i gian (ms) t?i ?a m?t k?t n?i ???c gi? idle (kh\uFFFDng s? d?ng) trong pool tr??c khi b? ?\uFFFDng.
#? ?\uFFFDy l\uFFFD 60 gi\uFFFDy.
spring.datasource.hikari.idle-timeout=60000
#Th?i gian (ms) t?i ?a m\uFFFD m?t k?t n?i ???c gi? trong pool k? t? l\uFFFDc t?o ra, b?t k? n\uFFFD c\uFFFD ?ang s? d?ng hay idle.
#? ?\uFFFDy l\uFFFD 180.000 ms (3 ph\uFFFDt)
spring.datasource.hikari.max-lifetime=600000

# ========== LOGGING ==========
# D\uFFFDng duy nh?t ?? debug
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.engine.jdbc.connections=DEBUG